### ISSUE TITLE
Support base paths on webadmin

### ISSUE THREAD

**Issue by optix2000** [znc/znc#814] opened 2015-01-12 09:53 UTC
As it is now, all the base paths are hard coded to "/", which breaks everything if you try to run the webadmin behind a proxy (eg. nginx) and change the base path.
ie, remapping "http://example.com/znc" to "http://127.0.0.1:6667"

All the CSS, which is assumed to be on "/pub/_default_.css", actually exists on "/znc/pub/_default_.css", and links (such as /login), don't route to the right place.

**Comment by md-5** [comment] 2015-01-12 09:59
Not as of 1.5 (currently unreleased / use nightlies)
https://github.com/znc/znc/commit/4376b373d841253c8a6dac4207567d4661724432

**Comment by optix2000** [comment] 2015-01-12 16:40
I just noticed it was a config option for 1.6 on the wiki (along with customizing SSL, yay!).

Is 1.5 the latest release? The wiki says 1.4 is latest.

**Comment by dgw** [comment] 2015-01-12 16:41
Odd points are development versions, even points are stable releases. 1.4 is the latest stable release, but you can run 1.5 (git/devel) by checking out and compiling the code in this repo.

**Comment by jpnurmi** [comment] 2015-01-12 16:42
ZNC versioning strikes again: https://github.com/znc/znc/issues/748

**Comment by KindOne-** [comment] 2015-01-12 20:56
@jpnurmi http://wiki.znc.in/Configuration#Added_in_1.6 Could just name it "1.5 (git/nightly)" instead of "1.6", since 1.6 is not released yet.

**Comment by DarthGandalf** [comment] 2015-01-12 21:50
Duplicate of #480

**Closed by DarthGandalf** 2015-01-12 21:50 UTC
