### ISSUE TITLE
route_replies irssi disconnect when hitting timeouts

### ISSUE THREAD

**Issue by twouters** [znc/znc#1341] opened 2016-11-09 10:56 UTC
Not exactly sure what happened here, but due to connectivity issues with the irc network that I'm connected to I was getting the following warning a few times "This module hit a timeout which is probably a connectivity issue.".
Irssi reported an increasing Lag while this happened, and eventually disconnected from znc with the following message: "No PONG reply from server my.znc.host in 301 seconds, disconnecting".
I have no idea why irssi disconnects from znc during stability issues between znc and the irc server while znc was able to keep the connection to the irc server active.

**Comment by DarthGandalf** [comment] 2016-11-17 23:28
version?
logs of `znc -D`? (remove passwords from there)

**Comment by RealKindOne** [comment] 2016-11-18 02:00
Kinda sure this is a duplicate of #1299

**Comment by welwood08** [comment] 2016-11-21 16:03
Assuming this is a duplicate, I'm pretty sure I was experiencing it before I manually applied psychon's solution over 1.6.3 (ie if a 1.6.4 is imminent it seems worthwhile to backport the fix from master).

**Comment by DarthGandalf** [comment] 2016-11-23 00:14
Done.

**Closed by DarthGandalf** 2016-11-23 00:14 UTC
