### ISSUE TITLE
ZNC 1.6.1 release archive doesn't contain submodules

### ISSUE THREAD

**Issue by michaelforge** [znc/znc#1135] opened 2015-09-29 09:50 UTC
`make` is not happening on release archive (https://github.com/znc/znc/releases/tag/znc-1.6.1):

```
root@services163:~/znc-znc-1.6.1/znc# make
Packing man page znc.1.gz...
Packing man page znc-buildmod.1.gz...
It looks like git submodules are not initialized. Run: git submodule update --init --recursive
make: *** [third_party/Csocket/Csocket.h] Error 1
```

The issue is: release archive does not contain '.git' folder, so there is no way to do `git submodule update --init --recursive`.

Solved by using not release archive, but git cloning particular release commit (in this case: aa6e7e7).

Could be reference to #806

**Comment by Mikaela** [comment] 2015-09-29 09:51
This issue is invalid and caused by ZNC using submodules which GitHub doesn't support with those zip/tarballs, but they cannot be disabled.

Please download ZNC from http://znc.in/releases/ instead.

**Comment by michaelforge** [comment] 2015-09-29 09:52
I see. Thanks =]
Probably there is no reason to keep releases on GitHub then.

**Comment by Mikaela** [comment] 2015-09-29 09:54
> Probably there is no reason to keep releases on GitHub then.

I was unclear at first sorry, the tar/zip files are automatically generated by GitHub and they cannot be disabled. I have requested disabling them at least once from GitHub support.

This issue doesn't affect only ZNC, but also Atheme, https://github.com/atheme/atheme/issues/382.

**Comment by michaelforge** [comment] 2015-09-29 09:56
@Mikaela 
Thanks for explanation. Sorry for taking your time then :sweat_smile:

**Comment by Mikaela** [comment] 2015-09-29 09:56
You're welcome, no problem. Could you close this next to the comment box?

**Closed** 2015-09-29 09:56 UTC
