### ISSUE TITLE
Long time between time-out and reconnection of znc server IP change

### ISSUE THREAD

**Issue by DominusExult** [znc/znc#327] opened 2013-04-22 13:53 UTC
My ZNC server (raspberry pi, znc 1.0) is connected to a DSL router. From time to time, the DSL synchronization fails and the router goes through the synchroniazation steps and gets a new IP from the ISP.
This results in a long delay between the time the ZNC server times out and reconnects.
An example from #exult on freenode:
[22:54:40] <-- Dominus has left IRC (Read error: Operation timed out)
[23:02:20] --> Dominus has joined #exult

According to the router logs, the new IP was given at 22:53:45.

I thought this to be an issue with the Raspberry but when I had ZNC running on my Mac Mini the delay was about the same time.

**Comment by DarthGandalf** [comment] 2015-08-27 07:09
Duplicate of #979

**Closed by DarthGandalf** 2015-08-27 07:09 UTC
