### ISSUE TITLE
Adding SSL server without SSL support silently fails on the Web control panel.

### ISSUE THREAD

**Issue by dan2wik** [znc/znc#1293] opened 2016-07-10 07:22 UTC
Adding an SSL server to the web interface without compiling SSL support silently does not add the server.
##

**Comment by evil-dan2wik** [comment] 2016-07-10 07:28
OS: Ubuntu 16.04
Version output:
ZNC 1.7.x-nightly-20160706-5dd20936 - http://znc.in
IPv6: yes, SSL: no, DNS: threads, charset: no, build: autoconf, i18n: no

**Comment by Mikaela** [comment] 2016-07-10 07:32
Duplicate of https://github.com/znc/znc/issues/1118 .

**Comment by DarthGandalf** [comment] 2016-11-16 15:42
While fixing this, also need to check behavior of `*status` and `*controlpanel`

**Closed** 2021-04-23 00:59 UTC
