### ISSUE TITLE
znc tries to use default ssl port if znc does not support ssl. 

### ISSUE THREAD

**Issue by ghost** [znc/znc#1118] opened 2015-09-24 06:24 UTC
`ZNC 1.7.x-git-441-d66cb36 - http://znc.in`
`IPv6: yes, SSL: no, DNS: threads, charset: yes`

`./configure --disable-openssl --enable-run-from-source`

https://gist.github.com/KindOne-/a337435bf98379ed641a (Yes, I know a password is in it)

I think znc should at least throw some error or disable the 'ssl by default port'. if built without ssl.
##

**Comment by Mikaela** [comment] 2015-09-24 06:31
How this appears to user is that when user adds server `chat.freenode.net +7000` in webadmin or `*status`, the server appears as `n/a`.

This was just troubleshooted at #znc for a long time.

Clear error message would be "Recompile ZNC with SSL support or use plaintext port."

**Comment by DarthGandalf** [comment] 2016-11-16 15:41
The gist is not available.
Marking as duplicate of #1293 which has a non-ghost reporter.

**Closed by DarthGandalf** 2016-11-16 15:41 UTC
