### ISSUE TITLE
znc disconnecting from irc network at regular intervals

### ISSUE THREAD

**Issue by gesa** [znc/znc#1650] opened 2019-04-09 20:47 UTC
So sorry to resurrect the past (specifically #1448 & #487) but I'm still having this disconnection problem despite a fix being released in 1.7.0 iirc. 

```
|⇒  znc --version
ZNC 1.7.1 - https://znc.in
IPv6: yes, SSL: yes, DNS: threads, charset: yes, i18n: no, build: autoconf
```

I get disconnected every 2 hours, 14 minutes, and some odd seconds. Relevant output of `znc -D`:

```
[2019-04-09 13:13:25.825934] (gesa/freenode) ZNC -> IRC [PING :ZNC]
[2019-04-09 13:13:55.826061] (gesa/freenode) ZNC -> IRC [PING :ZNC]
[2019-04-09 13:14:25.925821] (gesa/freenode) ZNC -> IRC [PING :ZNC]
[2019-04-09 13:14:27.601309] IRC::gesa::freenode == Timeout()
[2019-04-09 13:14:27.661716] IRC::gesa::freenode == Disconnected()
[2019-04-09 13:14:27.999566] (gesa/freenode) ZNC -> IRC [QUIT :👋🏻]
[2019-04-09 13:14:27.999691] Connecting user/network [gesa/freenode]
[2019-04-09 13:14:27.999702] TDNS: initiating resolving of [chat.freenode.net] and bindhost []
[2019-04-09 13:14:27.999716] ConnectQueueTimer done
[2019-04-09 13:14:28.014271] TDNS: IRC::gesa::freenode, connecting to [2a01:7e00::f03c:91ff:fee2:413b] using bindhost []
[2019-04-09 13:14:28.014320] src/Csocket.cpp:1281 Connect Failed. ERRNO [101] FD [10]
[2019-04-09 13:14:28.014338] IRC::gesa::freenode == SockError(101 Network is unreachable)
[2019-04-09 13:14:58.203602] Connecting user/network [gesa/freenode]
[2019-04-09 13:14:58.203678] TDNS: initiating resolving of [chat.freenode.net] and bindhost []
[2019-04-09 13:14:58.203718] ConnectQueueTimer done
[2019-04-09 13:14:58.204792] TDNS: IRC::gesa::freenode, connecting to [2a01:7e00::f03c:91ff:fee2:413b] using bindhost []
[2019-04-09 13:14:58.204895] src/Csocket.cpp:1281 Connect Failed. ERRNO [101] FD [10]
[2019-04-09 13:14:58.204931] IRC::gesa::freenode == SockError(101 Network is unreachable)
[2019-04-09 13:15:28.705189] Connecting user/network [gesa/freenode]
[2019-04-09 13:15:28.705266] TDNS: initiating resolving of [chat.freenode.net] and bindhost []
[2019-04-09 13:15:28.705304] ConnectQueueTimer done
[2019-04-09 13:15:28.718652] TDNS: IRC::gesa::freenode, connecting to [162.213.39.42] using bindhost []
[2019-04-09 13:15:28.740343] IRC::gesa::freenode == Connected()
```

**Comment by DarthGandalf** [comment] 2019-04-09 20:54
> I get disconnected every 2 hours, 14 minutes, and some odd seconds.

The only relevant line in the log is `[2019-04-09 13:14:27.601309] IRC::gesa::freenode == Timeout()` and it doesn't say much. Check your network connection. Anything happens with your router (NAT?) every 2 hours?

> 101 Network is unreachable

This is duplicate of #241 and not related to timeouts.

**Comment by gesa** [comment] 2019-04-09 21:09
Ugh it absolutely is my router’s NAT every two hours (evidently every 130 minutes according to all the complaints on the internet about it)

Sorry for wasting your time -_-

**Closed** 2019-04-09 21:09 UTC
