### ISSUE TITLE
Build broken with LibreSSL

### ISSUE THREAD

**Issue by brad0** [znc/znc#1198] opened 2015-11-29 00:15 UTC
With the current ZNC 1.6.2 release the build is still broken with LibreSSL. The copy of Csocket was updated to include the fixes for the lack of SSLv3 support but somehow this commit https://github.com/jimloco/Csocket/commit/5494c125599fbe02e6d7839d1a8ebeffe3e77907 is missing from the copy included with ZNC even though the commit in question comes with Csocket proper from upstream.

**Comment by DarthGandalf** [comment] 2015-11-29 01:04
Ah, that fix was in wrong branch...

**Comment by Mikaela** [comment] 2015-11-29 09:21
Nice, does this mean 1.6.3 (while 1.6.2 was released just to fix LibreSSL & OpenSSL that doesn't have SSLv3 compiled)?

**Comment by DarthGandalf** [comment] 2015-11-29 11:27
> 1.6.2 was released just to fix LibreSSL & OpenSSL

I advise you to check the ChangeLog again.

**Comment by Mikaela** [comment] 2015-11-29 12:05
> I advise you to check the ChangeLog again.

From what I understood the other fixes weren't that important and 1.6.2 would have waited a lot longer time without this issue existing (like was the case with 1.4). If I am wrong, I advice everyone to try communicating more clearly.

**Comment by DarthGandalf** [comment] 2015-11-29 12:14
I wonder how you got such impression...

Some other changes are less important (e.g. help output of `*perform`), but some other changes are more important (e.g. crash-fix)

http://wiki.znc.in/ChangeLog/1.6.2 doesn't even mention LibreSSL, only OpenSSL

**Comment by DarthGandalf** [comment] 2016-02-08 20:37
I cherry-picked it to the 1.6 branch (https://github.com/jimloco/Csocket/commit/8b6636f04272e10dd52acb9081564dfc13b56b4b), so closing as duplicate of #594

**Closed by DarthGandalf** 2016-02-08 20:37 UTC
