### ISSUE TITLE
Support for TLSv1.3

### ISSUE THREAD

**Issue by DoctorD90** [znc/znc#1804] opened 2021-08-19 14:01 UTC
Currently TLSv1.3 is not supported:

https://github.com/znc/znc/blob/master/src/znc.cpp#L2003

In the current build only TLS1.2 is usable (being TLS1.3 not available)

**Comment by DarthGandalf** [comment] 2021-08-19 14:03
Dupe of #1512

**Closed by DarthGandalf** 2021-08-19 14:03 UTC
