### ISSUE TITLE
BACKLOG command

### ISSUE THREAD

**Issue by SoniEx2** [znc/znc#1373] opened 2017-01-28 18:54 UTC
Would be neat if 005 announced a BACKLOG command, to dynamically fetch more backlog (instead of getting the whole backlog all at once).

I have no idea how such a BACKLOG command would work, but I think it'd at least take a nick/channel argument, a line count, and maybe require server-time or message-ids to be enabled and stuff (otherwise the server would have to keep track of how much backlog the user has requested, which wouldn't be the end of the world but eh, sounds painful).

Backlogs wouldn't be automatically fetched when a client connects - clients would have to explicitly request them. This would save bandwidth.

(Why not post this on IRCv3? Well because I'm banned from IRCv3. And this isn't very useful for your standard IRCd, it's more useful for bouncers.)

**Comment by DarthGandalf** [comment] 2017-01-28 22:23
This doesn't belong here. It's not a ZNC issue.
Also, this is duplicate of https://github.com/ircv3/ircv3-specifications/pull/292

> Well because I'm banned from IRCv3

Keep posting nonsense here, and you'll be banned here as well.

**Closed by DarthGandalf** 2017-01-28 22:23 UTC

**Comment by SoniEx2** [comment] 2017-01-28 23:01
Neat. Would be very useful for my IRC-based twitter client. Can you fast-track it?
