### ISSUE TITLE
[Feature Request] Add ModNode

### ISSUE THREAD

**Issue by McDeffice** [znc/znc#1727] opened 2020-06-14 13:58 UTC
I suggest implementing Node.Js support in modules such as modPerl, modpython or modtcl.

I am convinced that for various reasons the support of Node.Js in ZNC could open new horizons to ZNC (and to Node.Js)

Is it possible ? tks

**Comment by psychon** [comment] 2020-06-14 14:22
I guess that something like `modjavascript` using V8 could be possible. Interacting with Node.js however is unlikely. You can also not use any perl/python/tcl library with modperl/modpython/modtcl, but only stuff that integrates with ZNC's main loop. Integrating all of Node.js sounds impossible (= an immense task and the result would likely be brittle and break often).

**Comment by DarthGandalf** [comment] 2020-06-14 15:31
Duplicate of  #1086

**Closed by DarthGandalf** 2020-06-14 15:31 UTC
