### ISSUE TITLE
Allow ordering channels [$15]

### ISSUE THREAD

**Issue by kylef** [znc/znc#104] opened 2012-01-16 07:47 UTC
A few people have requested/complained that ZNC doesn't order channels how they wish.

Previously ZNC written its configs differently so that channels were saved in order they were added, I changed it to use CConfig to write the config. This doesn't store them in the same order.

We could implement some kind of index on the channels in the config. This will allow us to read them and place them in the same order as before.

```
/msg *status movechan #channel <new-index>
```

The webadmin could also be updated to allow moving channels up/down.

I have created an issue so we can discuss this further and decide if we should implement this, and how.

Related: #89
##

**Comment by curtisz** [comment] 2015-01-20 19:27
+1 for my own particular order (and not just alphabetical, which does me no good). Just a cursory examination of m0vie's [commit](https://github.com/m0vie/znc/commit/a697fa2e5394cd26de8d5dc4426b15a252be0c5b) looks like it gets the job done. Is there a particular reason this hasn't been merged yet? Sorting channels is an annoying task, and the referenced commit makes it look like this is also an unnecessary task.

**Comment by DarthGandalf** [comment] 2015-01-20 20:32
@curtisz that commit adds a new setting to znc.conf with the order. But znc.conf already contains channels in some order, why a new setting?
Also see comments in #238

**Comment by curtisz** [comment] 2015-01-20 20:57
Down at the bottom (starting src/IRCNetwork.cpp:797) it appears to sort the channels according to the order they were given. As it stands, znc.conf does not pay attention to channel ordering, regardless of how they're ordered in there. Also, I don't care if a connected client has the ability to sort channels. I want ZNC to sort the channels.

**Comment by DarthGandalf** [comment] 2015-01-20 21:04
> As it stands, ZNC does not pay attention to channel ordering, regardless of how they're ordered in znc.conf

And that needs to be fixed, instead of introducing a new setting.

**Comment by curtisz** [comment] 2015-01-20 21:11
My perspective is that I don't see the order in znc.conf as innately specifying a particular order as much as just being a set of channels. Preferring the explicit over implicit, I think an explicit setting here would be nice. Also, I would think it's probably easier to get ZNC to exhibit the desired behavior with an explicit setting, though I have no idea how ZNC handles the channel set internally. It's a new setting, sure, but there isn't really an existing one.

**Comment by sjau** [comment] 2015-01-20 21:13
@DarthGandalf 
TBH, I don't really care how it's done... if existing settings can be (ab)used or new setting needs to be introduced... I'd just love if it gets the ability to have defined channel order list...

**Comment by curtisz** [comment] 2015-01-20 21:47
And at the end of the day, philosophy about new settings aside, the code right there in m0vie's commit looks like it gives ZNC the desired behavior.

**Comment by zapy85** [comment] 2017-03-21 20:22
Upped the bounty with 15$, so there is a 30$ bounty for whoever fixes this know (And adds the functionality to the web interface to change the order)

**Comment by MetaNova** [comment] 2019-11-14 22:15
Might want to update the title, it's now $45, as well as editing the link: [https://www.bountysource.com/issues/696-allow-ordering-channels](https://www.bountysource.com/issues/696-allow-ordering-channels) @kylef

**Comment by njhanley** [comment] 2020-07-06 23:43
@DarthGandalf Could you explain what changes are needed for #238 to be merged?
> > As it stands, ZNC does not pay attention to channel ordering, regardless of how they're ordered in znc.conf
> 
> And that needs to be fixed, instead of introducing a new setting.

Config entries appear to be sorted lexicographically by design. Are you saying that the config system should instead respect the order in znc.conf for all entries?

**Comment by DarthGandalf** [comment] 2020-07-07 17:45
> sorted lexicographically by design

By what design?

> Are you saying that the config system should instead respect the order in znc.conf for all entries?

Yep. It only matters for channels though.

**Closed** 2020-10-04 20:08 UTC
Labels: Bountysource, Feature
