### ISSUE TITLE
MaxNetworks=1 does not allow a network to be created

### ISSUE THREAD

**Issue by simpleauthority** [znc/znc#1622] opened 2018-11-29 05:49 UTC
Having MaxNetworks=1 set for a user does not allowed said user to create a network. It immediately notes the network limit is reached.

**Comment by DarthGandalf** [comment] 2018-11-29 09:23
Looks like duplicate of #1584 
The workaround is to create the network via controlpanel module, not in webadmin

**Closed by DarthGandalf** 2018-11-29 09:23 UTC
